### ISSUE TITLE
Keep ReiNand.dat ?

### ISSUE THREAD

**Issue by gnmmarechal** [Hikiruka/ReiNand-Plus#2]
`make: *** No rule to make target 'out/rei/', needed by 'out/ReiNand+.dat'.  Stop.`

That's what make outputs for make launcher or make all (after making a9lh).

Noticed this when I added this to my buildscripts.

**Comment by Pixilate** [comment]
Try it now.  I've changed the makefile a bit seeing as there were still some "/rei/".  Might've been the issue

**Comment by gnmmarechal** [comment]
```
'data/firmware.bin' -> 'out/rei+/firmware.bin'
'data/splash.bin' -> 'out/rei+/splash.bin'
make[1]: *** cakehax: No such file or directory.  Stop.
Makefile:56: recipe for target 'out/ReiNand+.dat' failed
make: *** [out/ReiNand+.dat] Error 2
```

**Comment by gnmmarechal** [comment]
huh. I DID do a recursive clone, so I'm not missing anything afaik

**Comment by Pixilate** [comment]
"make[1]: **\* cakehax: No such file or directory.  Stop.
Makefile:56: recipe for target 'out/ReiNand+.dat' failed
make: **\* [out/ReiNand+.dat] Error 2"

 I'm thinking  this may be a directory  issue. I'll  look into it  later as I'm busy

**Comment by Pixilate** [comment]
How's using a loader similar  to Luma's sounding, Unless  keeping  the .dat is better ?

**Comment by gnmmarechal** [comment]
Frankly.... Well, I don't have any use for the .dat myself.

**Comment by CrimsonMaple** [comment]
Reinand needs the .dat to load from. Luma does as well. It just creates it on the fly. Its where the base .o and .h files are stored.

**Comment by Pixilate** [comment]
@CrimsonMaple This is deciding if i should drop emunand support. with the new advancements, most of the scene is running on A9LH

**Comment by CrimsonMaple** [comment]
No. Emunand support is a feature used by many and should be kept for legacy reasons.

**Comment by Pixilate** [comment]
Alright.
