### ISSUE TITLE
Makefile Outputs Directory Rei+ to a file.

### ISSUE THREAD

**Issue by CrimsonMaple** [Hikiruka/ReiNand-Plus#4]

**Comment by CrimsonMaple** [comment]
Fixed in my Fork. Make something that compiles next time, before you release.

**Comment by Pixilate** [comment]
Do note, I've never released a binary yet. I've reverted to an earlier version of my modifications, and  I'm fixing  what I've done wrong

**Comment by CrimsonMaple** [comment]
Dont worry about it. Merge my changes.
